version: "3"

includes:
  brew:
    taskfile: ~/setup/taskfiles/brew.yaml
    aliases: [b]
    dir: ~/setup

  chezmoi:
    taskfile: ~/setup/taskfiles/chezmoi.yaml
    aliases: [c]
    dir: ~/setup

  nix:
    taskfile: ~/setup/taskfiles/nix.yaml
    aliases: [n]
    dir: ~/setup

  ssh:
    taskfile: ~/setup/taskfiles/ssh.yaml
    aliases: [s]
    dir: ~/setup

  # vscode:
  #   taskfile: ~/setup/taskfiles/vscode.yaml
  #   aliases: [vs]
  #   dir: ~/setup

tasks:
  setup:
    aliases: [s]
    cmds:
      - task: chezmoi:apply
      - task: brew:bundle
